# coding: utf-8

"""
    Resend

    Resend is the email platform for developers.

    The version of the OpenAPI document: 1.1.0
    Generated by: https://konfigthis.com
"""

import unittest

import os
from pprint import pprint
from resend_python_sdk import Resend

class TestSimple(unittest.TestCase):
    def setUp(self):
        pass

    def test_client(self):
        resend = Resend(
        
            access_token = 'YOUR_BEARER_TOKEN'
        )
        self.assertIsNotNone(resend)

    def tearDown(self):
        pass


if __name__ == "__main__":
    unittest.main()
