# coding: utf-8

"""
    Resend

    Resend is the email platform for developers.

    The version of the OpenAPI document: 1.1.0
    Generated by: https://konfigthis.com
"""

import unittest

import resend_python_sdk
from resend_python_sdk.model.list_api_keys_response import ListApiKeysResponse
from resend_python_sdk import configuration


class TestListApiKeysResponse(unittest.TestCase):
    """ListApiKeysResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
