# coding: utf-8

"""
    Resend

    Resend is the email platform for developers.

    The version of the OpenAPI document: 1.1.0
    Generated by: https://konfigthis.com
"""

import unittest

import resend_python_sdk
from resend_python_sdk.model.create_audience_response_success import CreateAudienceResponseSuccess
from resend_python_sdk import configuration


class TestCreateAudienceResponseSuccess(unittest.TestCase):
    """CreateAudienceResponseSuccess unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
