# coding: utf-8

"""
    Resend

    Resend is the email platform for developers.

    The version of the OpenAPI document: 1.1.0
    Generated by: https://konfigthis.com
"""

from resend_python_sdk.paths.api_keys.post import CreateNewKeyRaw
from resend_python_sdk.paths.api_keys.get import GetListRaw
from resend_python_sdk.paths.api_keys_api_key_id.delete import RemoveExistingKeyRaw


class APIKeysApiRaw(
    CreateNewKeyRaw,
    GetListRaw,
    RemoveExistingKeyRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
