# coding: utf-8

"""
    Resend

    Resend is the email platform for developers.

    The version of the OpenAPI document: 1.1.0
    Generated by: https://konfigthis.com
"""

from resend_python_sdk.paths.audiences.post import CreateContactListRaw
from resend_python_sdk.paths.audiences.get import GetListRaw
from resend_python_sdk.paths.audiences_id.get import GetSingleAudienceRaw
from resend_python_sdk.paths.audiences_id.delete import RemoveExistingAudienceRaw


class AudiencesApiRaw(
    CreateContactListRaw,
    GetListRaw,
    GetSingleAudienceRaw,
    RemoveExistingAudienceRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
