# coding: utf-8

"""
    Resend

    Resend is the email platform for developers.

    The version of the OpenAPI document: 1.1.0
    Generated by: https://konfigthis.com
"""

from resend_python_sdk.paths.domains.post import CreateNewDomain
from resend_python_sdk.paths.domains.get import GetList
from resend_python_sdk.paths.domains_domain_id.get import GetSingleDomain
from resend_python_sdk.paths.domains_domain_id.delete import RemoveDomain
from resend_python_sdk.paths.domains_domain_id.patch import UpdateExistingDomain
from resend_python_sdk.paths.domains_domain_id_verify.post import VerifyDomain
from resend_python_sdk.apis.tags.domains_api_raw import DomainsApiRaw


class DomainsApi(
    CreateNewDomain,
    GetList,
    GetSingleDomain,
    RemoveDomain,
    UpdateExistingDomain,
    VerifyDomain,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: DomainsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = DomainsApiRaw(api_client)
