# coding: utf-8

"""
    Resend

    Resend is the email platform for developers.

    The version of the OpenAPI document: 1.1.0
    Generated by: https://konfigthis.com
"""

from resend_python_sdk.paths.domains.post import CreateNewDomainRaw
from resend_python_sdk.paths.domains.get import GetListRaw
from resend_python_sdk.paths.domains_domain_id.get import GetSingleDomainRaw
from resend_python_sdk.paths.domains_domain_id.delete import RemoveDomainRaw
from resend_python_sdk.paths.domains_domain_id.patch import UpdateExistingDomainRaw
from resend_python_sdk.paths.domains_domain_id_verify.post import VerifyDomainRaw


class DomainsApiRaw(
    CreateNewDomainRaw,
    GetListRaw,
    GetSingleDomainRaw,
    RemoveDomainRaw,
    UpdateExistingDomainRaw,
    VerifyDomainRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
