# coding: utf-8

"""
    Resend

    Resend is the email platform for developers.

    The version of the OpenAPI document: 1.1.0
    Generated by: https://konfigthis.com
"""

from resend_python_sdk.paths.emails_email_id.get import GetSingleEmail
from resend_python_sdk.paths.emails.post import SendEmail
from resend_python_sdk.paths.emails_batch.post import TriggerBatchEmails
from resend_python_sdk.apis.tags.emails_api_raw import EmailsApiRaw


class EmailsApi(
    GetSingleEmail,
    SendEmail,
    TriggerBatchEmails,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: EmailsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = EmailsApiRaw(api_client)
