# coding: utf-8

"""
    Resend

    Resend is the email platform for developers.

    The version of the OpenAPI document: 1.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredApiKey(TypedDict):
    pass

class OptionalApiKey(TypedDict, total=False):
    # The ID of the API key.
    id: str

    # The name of the API key.
    name: str

    # The date and time the API key was created.
    created_at: datetime

class ApiKey(RequiredApiKey, OptionalApiKey):
    pass
