# coding: utf-8

"""
    Resend

    Resend is the email platform for developers.

    The version of the OpenAPI document: 1.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredAttachment(TypedDict):
    pass

class OptionalAttachment(TypedDict, total=False):
    # Content of an attached file.
    content: typing.IO

    # Name of attached file.
    filename: str

    # Path where the attachment file is hosted
    path: str

class Attachment(RequiredAttachment, OptionalAttachment):
    pass
