# coding: utf-8

"""
    Resend

    Resend is the email platform for developers.

    The version of the OpenAPI document: 1.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredCreateApiKeyResponse(TypedDict):
    pass

class OptionalCreateApiKeyResponse(TypedDict, total=False):
    # The ID of the API key.
    id: str

    # The token of the API key.
    token: str

class CreateApiKeyResponse(RequiredCreateApiKeyResponse, OptionalCreateApiKeyResponse):
    pass
