# coding: utf-8

"""
    Resend

    Resend is the email platform for developers.

    The version of the OpenAPI document: 1.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredCreateContactOptions(TypedDict):
    # Email address of the contact.
    email: str

class OptionalCreateContactOptions(TypedDict, total=False):
    # First name of the contact.
    first_name: str

    # Last name of the contact.
    last_name: str

    # Indicates if the contact is unsubscribed.
    unsubscribed: bool

    # Unique identifier of the audience to which the contact belongs.
    audience_id: str

class CreateContactOptions(RequiredCreateContactOptions, OptionalCreateContactOptions):
    pass
