# coding: utf-8

"""
    Resend

    Resend is the email platform for developers.

    The version of the OpenAPI document: 1.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredCreateApiKeyRequest(TypedDict):
    # The API key name.
    name: str

class OptionalCreateApiKeyRequest(TypedDict, total=False):
    # The API key can have full access to Resend’s API or be only restricted to send emails. * full_access - Can create, delete, get, and update any resource. * sending_access - Can only send emails.
    permission: str

    # Restrict an API key to send emails only from a specific domain. Only used when the permission is sending_acces.
    domain_id: str

class CreateApiKeyRequest(RequiredCreateApiKeyRequest, OptionalCreateApiKeyRequest):
    pass
