# coding: utf-8

"""
    Resend

    Resend is the email platform for developers.

    The version of the OpenAPI document: 1.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredDomainRecord(TypedDict):
    pass

class OptionalDomainRecord(TypedDict, total=False):
    # The type of record.
    record: str

    # The name of the record.
    name: str

    # The type of record.
    type: str

    # The time to live for the record.
    ttl: str

    # The status of the record.
    status: str

    # The value of the record.
    value: str

    # The priority of the record.
    priority: int

class DomainRecord(RequiredDomainRecord, OptionalDomainRecord):
    pass
