# coding: utf-8

"""
    Resend

    Resend is the email platform for developers.

    The version of the OpenAPI document: 1.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from resend_python_sdk.type.domain_record import DomainRecord

class RequiredDomain(TypedDict):
    pass

class OptionalDomain(TypedDict, total=False):
    # The type of object.
    object: str

    # The ID of the domain.
    id: str

    # The name of the domain.
    name: str

    # The status of the domain.
    status: str

    # The date and time the domain was created.
    created_at: datetime

    # The region where the domain is hosted.
    region: str

    records: typing.List[DomainRecord]

class Domain(RequiredDomain, OptionalDomain):
    pass
