# coding: utf-8

"""
    Resend

    Resend is the email platform for developers.

    The version of the OpenAPI document: 1.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from resend_python_sdk.type.email_bcc import EmailBcc
from resend_python_sdk.type.email_cc import EmailCc
from resend_python_sdk.type.email_reply_to import EmailReplyTo
from resend_python_sdk.type.email_to import EmailTo

RequiredEmail = TypedDict("RequiredEmail", {
    })

OptionalEmail = TypedDict("OptionalEmail", {
    # The type of object.
    "object": str,

    # The ID of the email.
    "id": str,

    "to": EmailTo,

    # The email address of the sender.
    "from": str,

    # The date and time the email was created.
    "created_at": datetime,

    # The subject line of the email.
    "subject": str,

    # The HTML body of the email.
    "html": str,

    # The plain text body of the email.
    "text": str,

    "bcc": EmailBcc,

    "cc": EmailCc,

    "reply_to": EmailReplyTo,

    # The status of the email.
    "last_event": str,
    }, total=False)

class Email(RequiredEmail, OptionalEmail):
    pass
