# coding: utf-8

"""
    Resend

    Resend is the email platform for developers.

    The version of the OpenAPI document: 1.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredGetContactResponseSuccess(TypedDict):
    pass

class OptionalGetContactResponseSuccess(TypedDict, total=False):
    # Type of the response object.
    object: str

    # Unique identifier for the contact.
    id: str

    # Email address of the contact.
    email: str

    # First name of the contact.
    first_name: str

    # Last name of the contact.
    last_name: str

    # Timestamp indicating when the contact was created.
    created_at: datetime

    # Indicates if the contact is unsubscribed.
    unsubscribed: bool

class GetContactResponseSuccess(RequiredGetContactResponseSuccess, OptionalGetContactResponseSuccess):
    pass
