# coding: utf-8

"""
    Resend

    Resend is the email platform for developers.

    The version of the OpenAPI document: 1.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredGetAudienceResponseSuccess(TypedDict):
    pass

class OptionalGetAudienceResponseSuccess(TypedDict, total=False):
    # The ID of the audience.
    id: str

    # The object of the audience.
    object: str

    # The name of the audience.
    name: str

    # The date that the object was created.
    created_at: str

class GetAudienceResponseSuccess(RequiredGetAudienceResponseSuccess, OptionalGetAudienceResponseSuccess):
    pass
