# coding: utf-8

"""
    Resend

    Resend is the email platform for developers.

    The version of the OpenAPI document: 1.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from resend_python_sdk.type.list_contacts_response_success_data_item import ListContactsResponseSuccessDataItem

ListContactsResponseSuccessData = typing.List[ListContactsResponseSuccessDataItem]
