# coding: utf-8

"""
    Resend

    Resend is the email platform for developers.

    The version of the OpenAPI document: 1.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredListAudiencesResponseSuccessDataItem(TypedDict):
    pass

class OptionalListAudiencesResponseSuccessDataItem(TypedDict, total=False):
    # Unique identifier for the audience.
    id: str

    # Name of the audience.
    name: str

    # Timestamp indicating when the audience was created.
    created_at: datetime

class ListAudiencesResponseSuccessDataItem(RequiredListAudiencesResponseSuccessDataItem, OptionalListAudiencesResponseSuccessDataItem):
    pass
