# coding: utf-8

"""
    Resend

    Resend is the email platform for developers.

    The version of the OpenAPI document: 1.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredRemoveContactResponseSuccess(TypedDict):
    pass

class OptionalRemoveContactResponseSuccess(TypedDict, total=False):
    # Type of the response object.
    object: str

    # Unique identifier for the removed contact.
    id: str

    # Indicates whether the contact was successfully deleted.
    deleted: bool

class RemoveContactResponseSuccess(RequiredRemoveContactResponseSuccess, OptionalRemoveContactResponseSuccess):
    pass
