# coding: utf-8

"""
    Resend

    Resend is the email platform for developers.

    The version of the OpenAPI document: 1.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from resend_python_sdk.type.attachment import Attachment
from resend_python_sdk.type.send_email_request_to import SendEmailRequestTo
from resend_python_sdk.type.tag import Tag

RequiredSendEmailRequest = TypedDict("RequiredSendEmailRequest", {
    # Sender email address. To include a friendly name, use the format \"Your Name <sender@domain.com>\".
    "from": str,

    "to": SendEmailRequestTo,

    # Email subject.
    "subject": str,
    })

OptionalSendEmailRequest = TypedDict("OptionalSendEmailRequest", {
    "tags": typing.List[Tag],

    # Bcc recipient email address. For multiple addresses, send as an array of strings.
    "bcc": str,

    # Cc recipient email address. For multiple addresses, send as an array of strings.
    "cc": str,

    # Reply-to email address. For multiple addresses, send as an array of strings.
    "reply_to": str,

    # The HTML version of the message.
    "html": str,

    # The plain text version of the message.
    "text": str,

    # Custom headers to add to the email.
    "headers": typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]],

    "attachments": typing.List[Attachment],
    }, total=False)

class SendEmailRequest(RequiredSendEmailRequest, OptionalSendEmailRequest):
    pass
