# coding: utf-8

"""
    Resend

    Resend is the email platform for developers.

    The version of the OpenAPI document: 1.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredUpdateContactOptions(TypedDict):
    pass

class OptionalUpdateContactOptions(TypedDict, total=False):
    # Email address of the contact.
    email: str

    # First name of the contact.
    first_name: str

    # Last name of the contact.
    last_name: str

    # Indicates the subscription status of the contact.
    unsubscribed: bool

class UpdateContactOptions(RequiredUpdateContactOptions, OptionalUpdateContactOptions):
    pass
