# coding: utf-8

"""
    Resend

    Resend is the email platform for developers.

    The version of the OpenAPI document: 1.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredUpdateDomainOptions(TypedDict):
    pass

class OptionalUpdateDomainOptions(TypedDict, total=False):
    # Enable or disable click tracking for the domain.
    click_tracking: bool

    # Enable or disable open tracking for the domain.
    open_tracking: bool

class UpdateDomainOptions(RequiredUpdateDomainOptions, OptionalUpdateDomainOptions):
    pass
