# coding: utf-8

"""
    Resend

    Resend is the email platform for developers.

    The version of the OpenAPI document: 1.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class ApiKey(BaseModel):
    # The ID of the API key.
    id: typing.Optional[str] = Field(None, alias='id')

    # The name of the API key.
    name: typing.Optional[str] = Field(None, alias='name')

    # The date and time the API key was created.
    created_at: typing.Optional[datetime] = Field(None, alias='created_at')
    class Config:
        arbitrary_types_allowed = True
