# coding: utf-8

"""
    Resend

    Resend is the email platform for developers.

    The version of the OpenAPI document: 1.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class CreateApiKeyRequest(BaseModel):
    # The API key name.
    name: str = Field(alias='name')

    # The API key can have full access to Resend’s API or be only restricted to send emails. * full_access - Can create, delete, get, and update any resource. * sending_access - Can only send emails.
    permission: typing.Optional[Literal["full_access", "sending_access"]] = Field(None, alias='permission')

    # Restrict an API key to send emails only from a specific domain. Only used when the permission is sending_acces.
    domain_id: typing.Optional[str] = Field(None, alias='domain_id')
    class Config:
        arbitrary_types_allowed = True
