# coding: utf-8

"""
    Resend

    Resend is the email platform for developers.

    The version of the OpenAPI document: 1.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class CreateAudienceOptions(BaseModel):
    # The name of the audience you want to create.
    name: str = Field(alias='name')
    class Config:
        arbitrary_types_allowed = True
