# coding: utf-8

"""
    Resend

    Resend is the email platform for developers.

    The version of the OpenAPI document: 1.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class DomainRecord(BaseModel):
    # The type of record.
    record: typing.Optional[str] = Field(None, alias='record')

    # The name of the record.
    name: typing.Optional[str] = Field(None, alias='name')

    # The type of record.
    type: typing.Optional[str] = Field(None, alias='type')

    # The time to live for the record.
    ttl: typing.Optional[str] = Field(None, alias='ttl')

    # The status of the record.
    status: typing.Optional[str] = Field(None, alias='status')

    # The value of the record.
    value: typing.Optional[str] = Field(None, alias='value')

    # The priority of the record.
    priority: typing.Optional[int] = Field(None, alias='priority')
    class Config:
        arbitrary_types_allowed = True
