# coding: utf-8

"""
    Resend

    Resend is the email platform for developers.

    The version of the OpenAPI document: 1.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from resend_python_sdk.pydantic.email_bcc import EmailBcc
from resend_python_sdk.pydantic.email_cc import EmailCc
from resend_python_sdk.pydantic.email_reply_to import EmailReplyTo
from resend_python_sdk.pydantic.email_to import EmailTo

class Email(BaseModel):
    # The type of object.
    object: typing.Optional[str] = Field(None, alias='object')

    # The ID of the email.
    id: typing.Optional[str] = Field(None, alias='id')

    to: typing.Optional[EmailTo] = Field(None, alias='to')

    # The email address of the sender.
    from_: typing.Optional[str] = Field(None, alias='from')

    # The date and time the email was created.
    created_at: typing.Optional[datetime] = Field(None, alias='created_at')

    # The subject line of the email.
    subject: typing.Optional[str] = Field(None, alias='subject')

    # The HTML body of the email.
    html: typing.Optional[str] = Field(None, alias='html')

    # The plain text body of the email.
    text: typing.Optional[str] = Field(None, alias='text')

    bcc: typing.Optional[EmailBcc] = Field(None, alias='bcc')

    cc: typing.Optional[EmailCc] = Field(None, alias='cc')

    reply_to: typing.Optional[EmailReplyTo] = Field(None, alias='reply_to')

    # The status of the email.
    last_event: typing.Optional[str] = Field(None, alias='last_event')
    class Config:
        arbitrary_types_allowed = True
