# coding: utf-8

"""
    Resend

    Resend is the email platform for developers.

    The version of the OpenAPI document: 1.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class ListDomainsItem(BaseModel):
    # The ID of the domain.
    id: typing.Optional[str] = Field(None, alias='id')

    # The name of the domain.
    name: typing.Optional[str] = Field(None, alias='name')

    # The status of the domain.
    status: typing.Optional[str] = Field(None, alias='status')

    # The date and time the domain was created.
    created_at: typing.Optional[datetime] = Field(None, alias='created_at')

    # The region where the domain is hosted.
    region: typing.Optional[str] = Field(None, alias='region')
    class Config:
        arbitrary_types_allowed = True
