# coding: utf-8

"""
    Resend

    Resend is the email platform for developers.

    The version of the OpenAPI document: 1.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class RemoveContactResponseSuccess(BaseModel):
    # Type of the response object.
    object: typing.Optional[str] = Field(None, alias='object')

    # Unique identifier for the removed contact.
    id: typing.Optional[str] = Field(None, alias='id')

    # Indicates whether the contact was successfully deleted.
    deleted: typing.Optional[bool] = Field(None, alias='deleted')
    class Config:
        arbitrary_types_allowed = True
