# coding: utf-8

"""
    Resend

    Resend is the email platform for developers.

    The version of the OpenAPI document: 1.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class UpdateDomainOptions(BaseModel):
    # Enable or disable click tracking for the domain.
    click_tracking: typing.Optional[bool] = Field(None, alias='click_tracking')

    # Enable or disable open tracking for the domain.
    open_tracking: typing.Optional[bool] = Field(None, alias='open_tracking')
    class Config:
        arbitrary_types_allowed = True
