# coding: utf-8

"""
    Resend

    Resend is the email platform for developers.

    The version of the OpenAPI document: 1.1.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class UpdateDomainResponseSuccess(BaseModel):
    # The ID of the updated domain.
    id: typing.Optional[str] = Field(None, alias='id')

    # The object type representing the updated domain.
    object: typing.Optional[str] = Field(None, alias='object')
    class Config:
        arbitrary_types_allowed = True
