# coding: utf-8

# flake8: noqa

"""
    Resend

    Resend is the email platform for developers.

    The version of the OpenAPI document: 1.1.0
    Generated by: https://konfigthis.com
"""

__version__ = "1.1.0"

# import ApiClient
from resend_python_sdk.api_client import ApiClient

# import Configuration
from resend_python_sdk.configuration import Configuration

# import exceptions
from resend_python_sdk.exceptions import OpenApiException
from resend_python_sdk.exceptions import ApiAttributeError
from resend_python_sdk.exceptions import ApiTypeError
from resend_python_sdk.exceptions import ApiValueError
from resend_python_sdk.exceptions import ApiKeyError
from resend_python_sdk.exceptions import ApiException

from resend_python_sdk.client import Resend
