# coding: utf-8
"""
    Resend

    Resend is the email platform for developers.

    The version of the OpenAPI document: 1.1.0
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from resend_python_sdk.client_custom import ClientCustom
from resend_python_sdk.configuration import Configuration
from resend_python_sdk.api_client import ApiClient
from resend_python_sdk.type_util import copy_signature
from resend_python_sdk.apis.tags.api_keys_api import APIKeysApi
from resend_python_sdk.apis.tags.audiences_api import AudiencesApi
from resend_python_sdk.apis.tags.contacts_api import ContactsApi
from resend_python_sdk.apis.tags.domains_api import DomainsApi
from resend_python_sdk.apis.tags.emails_api import EmailsApi



class Resend(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.api_keys: APIKeysApi = APIKeysApi(api_client)
        self.audiences: AudiencesApi = AudiencesApi(api_client)
        self.contacts: ContactsApi = ContactsApi(api_client)
        self.domains: DomainsApi = DomainsApi(api_client)
        self.emails: EmailsApi = EmailsApi(api_client)
